### ISSUE TITLE
Why force highest to be first in output?

### ISSUE THREAD

**Issue by chrisspiegl** [Kikobeats/aspect-ratio#17]
Hello, I just found this to calculate the aspect ratio of images to makes sure a suer selects a 16x9 or a 9x16 for upload.

However, I noticed that this library always puts whatever is the heigher value as the first in the output?

Aka: 

```
160x90 => 16:9
90x160 => 16:9
```

Which is not correct and isn't very useful? Why not keep the order on the final output? Is there a reason that I am not aware of?

I understand it may be necessary for the `gcd` calculation, but not for the final output. I think there it makes more sense to use the initial height/width as they were input.

**Comment by Kikobeats** [comment]
Hello, I'm not using this library for a while – Can you make a PR for fixing that behavior?

**Comment by chrisspiegl** [comment]
I submitted a pull request which should take care of all of this and make the library more as expected with the input parameters.

I also added tests to make sure the library now also understands vertical video resolutions and returns them correctly.

**Comment by Kikobeats** [comment]
shipped at `aspect-ratio@2.1.3` 🎉

**Comment by chrisspiegl** [comment]
Thanks for your fast support 👍 and the way you shipped this easily.

It's a small library but it's certainly usefull.
