### ISSUE TITLE
Cannot find module 'aspect-ratio'

### ISSUE THREAD

**Issue by trevorblades** [Kikobeats/aspect-ratio#8]
When I `npm install --save aspect-ratio`, the module at `index.js` doesn't show up. This is reproducible at https://npm.runkit.com/aspect-ratio. Without event writing any code and hitting "run" you'll see that it can't resolve the `aspect-ratio` module.

I looked at your `.npmignore` file and can't find anything suspicious but I can't imagine why your root file isn't being installed.

**Comment by Kikobeats** [comment]
Oh sorry, I forgot add `index.js` inside package.json#files:

https://github.com/Kikobeats/aspect-ratio/commit/4231a2042c176773527356e54ac7ec980bd9719b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45

PR incoming.

**Comment by trevorblades** [comment]
@Kikobeats no worries! That'll do the trick :) I didn't know to look at the `files` property before
